apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "homepage-2021"
  name: "homepage-2021"
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "homepage-2021"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "homepage-2021"
    spec:
      containers:
        - image: domano/homepage-2021
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 60
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 30
          name: "homepage-2021"
          env:
            - name: "REACT_APP_ENVIRONMENT"
              value: "PROD"
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 1000m
              memory: 2G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "homepage-2021"
  name: "homepage-2021"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: "homepage-2021"
  sessionAffinity: None
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-ingress
spec:
  rules:
  - host: "*.gomano.de"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: homepage-2021
            port:
              number: 80
